name: Update READMEs

on:
  push:
    paths:
      - '.github/scripts/listings.json'
  workflow_dispatch:

permissions:
  contents: write   # 👈 Required so the Actions bot can push commits

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: execute update_readme.py
        id: python_script
        run: python .github/scripts/update_readme.py

      - name: commit files
        if: success()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git pull
          git add README.md
          git diff-index --quiet HEAD || git commit -m "${{ steps.python_script.outputs.commit_message }}"

      - name: push changes
        if: success()
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Problem With Action
        run: echo "There was an error with the github action. ${{ steps.python_script.outputs.error_message }}"
        if: failure()
