name: Update Listings

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 1 * * *"  # Runs every day at 8 PM EST (1 AM UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run update script
        run: python .github/scripts/update_listings.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .github/scripts/listings.json
          git commit -m "Auto-update listings [skip ci]" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-update-listings
          branch-suffix: short-commit-hash
          title: "Auto-update listings"
          body: "This PR contains the daily automated internship listings update."
          base: main
          labels: automated-pr
          delete-branch: true
